version: '3.8'

services:
  license-service:
    container_name: license-service
    build:
      context: license-service
      dockerfile: Dockerfile
    image: microservices-in-action/license-service
    ports:
      - "8080:8080"

  configservice:
    container_name: configserver
    build:
      context: configserver
      dockerfile: Dockerfile
    image: microservices-in-action/configserver
    ports:
      - "8081:8081"